# Generated by Django 4.0.1 on 2022-01-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabawa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AddField(
            model_name='osoba',
            name='wiek',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
