# Generated by Django 4.0.1 on 2022-01-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabawa', '0002_alter_osoba_options_osoba_wiek'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='samochod',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
