# Generated by Django 4.0.1 on 2022-01-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabawa', '0003_osoba_samochod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=32)),
                ('nr_dom', models.PositiveIntegerField()),
                ('nr_miesz', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='osoba',
            name='samochod',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
