# Generated by Django 4.0.1 on 2022-01-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zabawa', '0004_adres_alter_osoba_samochod'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='adres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='zabawa.adres'),
        ),
    ]
