# Generated by Django 4.0.1 on 2022-01-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zabawa', '0005_osoba_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('kraj', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
            },
        ),
        migrations.CreateModel(
            name='Pilkarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('klub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zabawa.klub')),
            ],
            options={
                'verbose_name': 'Pilkarz',
                'verbose_name_plural': 'Pilkarze',
            },
        ),
    ]
