# Generated by Django 4.0.1 on 2022-01-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabawa', '0006_klub_pilkarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=32)),
                ('tag', models.ManyToManyField(related_name='tags', to='zabawa.Tag')),
            ],
        ),
    ]
