# Generated by Django 4.0.1 on 2022-01-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabawa', '0007_tag_ksiazka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='tag',
            field=models.ManyToManyField(related_name='ksiazki', to='zabawa.Tag'),
        ),
    ]
